/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.moolgoss.service 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class CommandType   {
    public static const MoveFormation:int = 1;

    public static const VALID_VALUES:Set = new Set(MoveFormation);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[MoveFormation] = "MoveFormation";

    }
  }
}
