/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.moolgoss.service {

  import flash.utils.ByteArray;
  import flash.utils.Dictionary;

  import org.apache.thrift.*;
  import org.apache.thrift.meta_data.*;
  import org.apache.thrift.protocol.*;


  public interface IMOOService {

    function Authenticate(name:String):void;
    function GetUpdate():UpdateData;
    function GetPlanets():Array;
    function GetFormations():Array;
    function IssueCommand(command:Command):void;
  }

}
